apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nimbus-idp-root
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/TempleInCloud/nimbus-idp.git
    targetRevision: main
    path: infra/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

