apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: ">=0.0.0"
    helm:
      releaseName: observability
      values: |
        alertmanager:
          enabled: false

        grafana:
          enabled: true
          persistence:
            enabled: false

        prometheus:
          prometheusSpec:
            retention: 2d
            storageSpec: {}

        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeEtcd:
          enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
